defaults:
    - _self_
    - data: vanilla_sequences
    - model: dnaddpmdiffusion
    - logger: wandb
    - trainer: default
    - callbacks: default
    - paths: default

seed: 42
train: True
test: True
ckpt_path: null
